/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The ApiEmpty model module.
 * @module model/ApiEmpty
 */

/**
 * Constructs a new <code>ApiEmpty</code>.
 * A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. The JSON representation for &#x60;Empty&#x60; is empty JSON object &#x60;{}&#x60;.
 * @alias module:model/ApiEmpty
 * @class
 */
var exports = function() {
  var _this = this;

};

/**
 * Constructs a <code>ApiEmpty</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/ApiEmpty} obj Optional instance to populate.
 * @return {module:model/ApiEmpty} The populated <code>ApiEmpty</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

    }
  return obj;
}




module.exports = exports;

