/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');


/**
 * Enum class ApiNoteKind.
 * @enum {}
 * @readonly
 */
var exports = {
  /**
   * value: "FINDING"
   * @const
   */
  "FINDING": "FINDING",
  /**
   * value: "KPI"
   * @const
   */
  "KPI": "KPI",
  /**
   * value: "CARD"
   * @const
   */
  "CARD": "CARD",
  /**
   * value: "CARD_CONFIGURED"
   * @const
   */
  "CARD_CONFIGURED": "CARD_CONFIGURED",
  /**
   * value: "SECTION"
   * @const
   */
  "SECTION": "SECTION"};

/**
 * Returns a <code>ApiNoteKind</code> enum value from a Javascript object name.
 * @param {Object} data The plain JavaScript object containing the name of the enum value.
 * @return {module:model/ApiNoteKind} The enum <code>ApiNoteKind</code> value.
 */
exports.constructFromObject = function(object) {
  return object;
}

module.exports = exports;
