/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The ApiProvider model module.
 * @module model/ApiProvider
 */

/**
 * Constructs a new <code>ApiProvider</code>.
 * Provides detailed description of a &#x60;Provider&#x60;.
 * @alias module:model/ApiProvider
 * @class
 */
var exports = function() {
  var _this = this;




};

/**
 * Constructs a <code>ApiProvider</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/ApiProvider} obj Optional instance to populate.
 * @return {module:model/ApiProvider} The populated <code>ApiProvider</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
      obj['name'] = ApiClient.convertToType(data['name'], 'String');
    }
      if (data.hasOwnProperty('id')) {
      obj['id'] = ApiClient.convertToType(data['id'], 'String');
    }
      if (data.hasOwnProperty('shared')) {
      obj['shared'] = ApiClient.convertToType(data['shared'], 'Boolean');
    }
    }
  return obj;
}

/**
 * @member {String} name
 */
exports.prototype['name'] = undefined;
/**
 * @member {String} id
 */
exports.prototype['id'] = undefined;
/**
 * True if this `Provider` can be shared by multiple accounts.
 * @member {Boolean} shared
 * @default true
 */
exports.prototype['shared'] = true;



module.exports = exports;

