/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The Context model module.
 * @module model/Context
 */

/**
 * Constructs a new <code>Context</code>.
 * @alias module:model/Context
 * @class
 */
var exports = function() {
  var _this = this;











};

/**
 * Constructs a <code>Context</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/Context} obj Optional instance to populate.
 * @return {module:model/Context} The populated <code>Context</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('region')) {
      obj['region'] = ApiClient.convertToType(data['region'], 'String');
    }
      if (data.hasOwnProperty('resource_crn')) {
      obj['resource_crn'] = ApiClient.convertToType(data['resource_crn'], 'String');
    }
      if (data.hasOwnProperty('resource_id')) {
      obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'String');
    }
      if (data.hasOwnProperty('resource_name')) {
      obj['resource_name'] = ApiClient.convertToType(data['resource_name'], 'String');
    }
      if (data.hasOwnProperty('resource_type')) {
      obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
    }
      if (data.hasOwnProperty('service_crn')) {
      obj['service_crn'] = ApiClient.convertToType(data['service_crn'], 'String');
    }
      if (data.hasOwnProperty('service_name')) {
      obj['service_name'] = ApiClient.convertToType(data['service_name'], 'String');
    }
      if (data.hasOwnProperty('environment_name')) {
      obj['environment_name'] = ApiClient.convertToType(data['environment_name'], 'String');
    }
      if (data.hasOwnProperty('component_name')) {
      obj['component_name'] = ApiClient.convertToType(data['component_name'], 'String');
    }
      if (data.hasOwnProperty('toolchain_id')) {
      obj['toolchain_id'] = ApiClient.convertToType(data['toolchain_id'], 'String');
    }
    }
  return obj;
}

/**
 * The IBM Cloud region
 * @member {String} region
 */
exports.prototype['region'] = undefined;
/**
 * The resource CRN (e.g. certificate CRN, image CRN)
 * @member {String} resource_crn
 */
exports.prototype['resource_crn'] = undefined;
/**
 * The resource ID, in case the CRN is not available
 * @member {String} resource_id
 */
exports.prototype['resource_id'] = undefined;
/**
 * The user-friendly resource name
 * @member {String} resource_name
 */
exports.prototype['resource_name'] = undefined;
/**
 * The resource type name (e.g. Pod, Cluster, Certificate, Image)
 * @member {String} resource_type
 */
exports.prototype['resource_type'] = undefined;
/**
 * The service CRN (e.g. CertMgr Instance CRN)
 * @member {String} service_crn
 */
exports.prototype['service_crn'] = undefined;
/**
 * The service name (e.g. CertMgr)
 * @member {String} service_name
 */
exports.prototype['service_name'] = undefined;
/**
 * The name of the environment the occurrence applies to
 * @member {String} environment_name
 */
exports.prototype['environment_name'] = undefined;
/**
 * The name of the component the occurrence applies to
 * @member {String} component_name
 */
exports.prototype['component_name'] = undefined;
/**
 * The id of the toolchain the occurrence applies to
 * @member {String} toolchain_id
 */
exports.prototype['toolchain_id'] = undefined;



module.exports = exports;

