/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');
var InlineResponse2001FindingNextSteps = require('./InlineResponse2001FindingNextSteps');
var InlineResponse2002FindingDataTransferred = require('./InlineResponse2002FindingDataTransferred');
var InlineResponse2002FindingNetworkConnection = require('./InlineResponse2002FindingNetworkConnection');



/**
 * The Finding model module.
 * @module model/Finding
 */

/**
 * Constructs a new <code>Finding</code>.
 * Finding provides details about a finding occurrence.
 * @alias module:model/Finding
 * @class
 */
var exports = function() {
  var _this = this;






};

/**
 * Constructs a <code>Finding</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/Finding} obj Optional instance to populate.
 * @return {module:model/Finding} The populated <code>Finding</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('severity')) {
      obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
    }
      if (data.hasOwnProperty('certainty')) {
      obj['certainty'] = ApiClient.convertToType(data['certainty'], 'String');
    }
      if (data.hasOwnProperty('next_steps')) {
      obj['next_steps'] = ApiClient.convertToType(data['next_steps'], [InlineResponse2001FindingNextSteps]);
    }
      if (data.hasOwnProperty('network_connection')) {
      obj['network_connection'] = InlineResponse2002FindingNetworkConnection.constructFromObject(data['network_connection']);
    }
      if (data.hasOwnProperty('data_transferred')) {
      obj['data_transferred'] = InlineResponse2002FindingDataTransferred.constructFromObject(data['data_transferred']);
    }
    }
  return obj;
}

/**
 * Note provider-assigned severity/impact ranking - LOW&#58; Low Impact - MEDIUM&#58; Medium Impact - HIGH&#58; High Impact
 * @member {module:model/Finding.SeverityEnum} severity
 */
exports.prototype['severity'] = undefined;
/**
 * Note provider-assigned confidence on the validity of an occurrence - LOW&#58; Low Certainty - MEDIUM&#58; Medium Certainty - HIGH&#58; High Certainty
 * @member {module:model/Finding.CertaintyEnum} certainty
 */
exports.prototype['certainty'] = undefined;
/**
 * Remediation steps for the issues reported in this finding. They override the note's next steps.
 * @member {Array.<module:model/InlineResponse2001FindingNextSteps>} next_steps
 */
exports.prototype['next_steps'] = undefined;
/**
 * @member {module:model/InlineResponse2002FindingNetworkConnection} network_connection
 */
exports.prototype['network_connection'] = undefined;
/**
 * @member {module:model/InlineResponse2002FindingDataTransferred} data_transferred
 */
exports.prototype['data_transferred'] = undefined;


  /**
   * Allowed values for the <code>severity</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SeverityEnum = {
    /**
     * value: "LOW"
     * @const
     */
    "LOW": "LOW",
    /**
     * value: "MEDIUM"
     * @const
     */
    "MEDIUM": "MEDIUM",
    /**
     * value: "HIGH"
     * @const
     */
    "HIGH": "HIGH"  };
  /**
   * Allowed values for the <code>certainty</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CertaintyEnum = {
    /**
     * value: "LOW"
     * @const
     */
    "LOW": "LOW",
    /**
     * value: "MEDIUM"
     * @const
     */
    "MEDIUM": "MEDIUM",
    /**
     * value: "HIGH"
     * @const
     */
    "HIGH": "HIGH"  };

module.exports = exports;

