/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The FindingCountValueType model module.
 * @module model/FindingCountValueType
 */

/**
 * Constructs a new <code>FindingCountValueType</code>.
 * @alias module:model/FindingCountValueType
 * @class
 * @param findingNoteNames {Array.<String>} the names of the finding note associated that act as filters for counting the occurrences
 */
var exports = function(findingNoteNames) {
  var _this = this;

  _this['finding_note_names'] = findingNoteNames;
};

/**
 * Constructs a <code>FindingCountValueType</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/FindingCountValueType} obj Optional instance to populate.
 * @return {module:model/FindingCountValueType} The populated <code>FindingCountValueType</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('finding_note_names')) {
      obj['finding_note_names'] = ApiClient.convertToType(data['finding_note_names'], ['String']);
    }
    }
  return obj;
}

/**
 * the names of the finding note associated that act as filters for counting the occurrences
 * @member {Array.<String>} finding_note_names
 */
exports.prototype['finding_note_names'] = undefined;



module.exports = exports;

