/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');
var InlineResponse200Providers = require('./InlineResponse200Providers');



/**
 * The InlineResponse200 model module.
 * @module model/InlineResponse200
 */

/**
 * Constructs a new <code>InlineResponse200</code>.
 * Response including listed providers
 * @alias module:model/InlineResponse200
 * @class
 */
var exports = function() {
  var _this = this;


};

/**
 * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse200} obj Optional instance to populate.
 * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('providers')) {
      obj['providers'] = ApiClient.convertToType(data['providers'], [InlineResponse200Providers]);
    }
    }
  return obj;
}

/**
 * @member {Array.<module:model/InlineResponse200Providers>} providers
 */
exports.prototype['providers'] = undefined;



module.exports = exports;

