/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The InlineResponse200CardElements model module.
 * @module model/InlineResponse200CardElements
 */

/**
 * Constructs a new <code>InlineResponse200CardElements</code>.
 * CardElement provides details about the elements of a Card
 * @alias module:model/InlineResponse200CardElements
 * @class
 * @param kind {module:model/InlineResponse200CardElements.KindEnum} Kind of element - NUMERIC&#58; Single numeric value - BREAKDOWN&#58; Breakdown of numeric values - TIME_SERIES&#58; Time-series of numeric values
 */
var exports = function(kind) {
  var _this = this;

  _this['kind'] = kind;

};

/**
 * Constructs a <code>InlineResponse200CardElements</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse200CardElements} obj Optional instance to populate.
 * @return {module:model/InlineResponse200CardElements} The populated <code>InlineResponse200CardElements</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('kind')) {
      obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
    }
      if (data.hasOwnProperty('default_time_range')) {
      obj['default_time_range'] = ApiClient.convertToType(data['default_time_range'], 'String');
    }
    }
  return obj;
}

/**
 * Kind of element - NUMERIC&#58; Single numeric value - BREAKDOWN&#58; Breakdown of numeric values - TIME_SERIES&#58; Time-series of numeric values
 * @member {module:model/InlineResponse200CardElements.KindEnum} kind
 */
exports.prototype['kind'] = undefined;
/**
 * The default time range of this card element
 * @member {module:model/InlineResponse200CardElements.DefaultTimeRangeEnum} default_time_range
 * @default '4d'
 */
exports.prototype['default_time_range'] = '4d';


  /**
   * Allowed values for the <code>kind</code> property.
   * @enum {String}
   * @readonly
   */
  exports.KindEnum = {
    /**
     * value: "NUMERIC"
     * @const
     */
    "NUMERIC": "NUMERIC",
    /**
     * value: "BREAKDOWN"
     * @const
     */
    "BREAKDOWN": "BREAKDOWN",
    /**
     * value: "TIME_SERIES"
     * @const
     */
    "TIME_SERIES": "TIME_SERIES"  };
  /**
   * Allowed values for the <code>default_time_range</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DefaultTimeRangeEnum = {
    /**
     * value: "1d"
     * @const
     */
    "1d": "1d",
    /**
     * value: "2d"
     * @const
     */
    "2d": "2d",
    /**
     * value: "3d"
     * @const
     */
    "3d": "3d",
    /**
     * value: "4d"
     * @const
     */
    "4d": "4d"  };

module.exports = exports;

