/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');
var InlineResponse2002Occurrences = require('./InlineResponse2002Occurrences');



/**
 * The InlineResponse2002 model module.
 * @module model/InlineResponse2002
 */

/**
 * Constructs a new <code>InlineResponse2002</code>.
 * Response including listed active occurrences.
 * @alias module:model/InlineResponse2002
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse2002} obj Optional instance to populate.
 * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('occurrences')) {
      obj['occurrences'] = ApiClient.convertToType(data['occurrences'], [InlineResponse2002Occurrences]);
    }
      if (data.hasOwnProperty('next_page_token')) {
      obj['next_page_token'] = ApiClient.convertToType(data['next_page_token'], 'String');
    }
    }
  return obj;
}

/**
 * The occurrences requested.
 * @member {Array.<module:model/InlineResponse2002Occurrences>} occurrences
 */
exports.prototype['occurrences'] = undefined;
/**
 * The next pagination token in the list response. It should be used as `page_token` for the following request. An empty value means no more results.
 * @member {String} next_page_token
 */
exports.prototype['next_page_token'] = undefined;



module.exports = exports;

