/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The InlineResponse2001RelatedUrl model module.
 * @module model/InlineResponse2001RelatedUrl
 */

/**
 * Constructs a new <code>InlineResponse2001RelatedUrl</code>.
 * Metadata for any related URL information
 * @alias module:model/InlineResponse2001RelatedUrl
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>InlineResponse2001RelatedUrl</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse2001RelatedUrl} obj Optional instance to populate.
 * @return {module:model/InlineResponse2001RelatedUrl} The populated <code>InlineResponse2001RelatedUrl</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
      obj['label'] = ApiClient.convertToType(data['label'], 'String');
    }
      if (data.hasOwnProperty('url')) {
      obj['url'] = ApiClient.convertToType(data['url'], 'String');
    }
    }
  return obj;
}

/**
 * @member {String} label
 */
exports.prototype['label'] = undefined;
/**
 * @member {String} url
 */
exports.prototype['url'] = undefined;



module.exports = exports;

