/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The InlineResponse200Providers model module.
 * @module model/InlineResponse200Providers
 */

/**
 * Constructs a new <code>InlineResponse200Providers</code>.
 * Provides a detailed description of a &#x60;Provider&#x60;.
 * @alias module:model/InlineResponse200Providers
 * @class
 * @param name {String} 
 * @param id {String} 
 */
var exports = function(name, id) {
  var _this = this;

  _this['name'] = name;
  _this['id'] = id;
};

/**
 * Constructs a <code>InlineResponse200Providers</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse200Providers} obj Optional instance to populate.
 * @return {module:model/InlineResponse200Providers} The populated <code>InlineResponse200Providers</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
      obj['name'] = ApiClient.convertToType(data['name'], 'String');
    }
      if (data.hasOwnProperty('id')) {
      obj['id'] = ApiClient.convertToType(data['id'], 'String');
    }
    }
  return obj;
}

/**
 * @member {String} name
 */
exports.prototype['name'] = undefined;
/**
 * @member {String} id
 */
exports.prototype['id'] = undefined;



module.exports = exports;

