/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The InlineResponse200FindingNextSteps model module.
 * @module model/InlineResponse200FindingNextSteps
 */

/**
 * Constructs a new <code>InlineResponse200FindingNextSteps</code>.
 * A remediation step description and associated URL
 * @alias module:model/InlineResponse200FindingNextSteps
 * @class
 */
var exports = function() {
  var _this = this;



};

/**
 * Constructs a <code>InlineResponse200FindingNextSteps</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/InlineResponse200FindingNextSteps} obj Optional instance to populate.
 * @return {module:model/InlineResponse200FindingNextSteps} The populated <code>InlineResponse200FindingNextSteps</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
      obj['title'] = ApiClient.convertToType(data['title'], 'String');
    }
      if (data.hasOwnProperty('url')) {
      obj['url'] = ApiClient.convertToType(data['url'], 'String');
    }
    }
  return obj;
}

/**
 * Title of this next step
 * @member {String} title
 */
exports.prototype['title'] = undefined;
/**
 * The URL associated to this next steps
 * @member {String} url
 */
exports.prototype['url'] = undefined;



module.exports = exports;

