/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The KpiType model module.
 * @module model/KpiType
 */

/**
 * Constructs a new <code>KpiType</code>.
 * KpiType provides details about a KPI note.
 * @alias module:model/KpiType
 * @class
 * @param aggregationType {module:model/KpiType.AggregationTypeEnum} The aggregation type of the KPI values. - SUM&#58; A single-value metrics aggregation type that sums up numeric values   that are extracted from KPI occurrences.
 */
var exports = function(aggregationType) {
  var _this = this;

  _this['aggregation_type'] = aggregationType;
};

/**
 * Constructs a <code>KpiType</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/KpiType} obj Optional instance to populate.
 * @return {module:model/KpiType} The populated <code>KpiType</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('aggregation_type')) {
      obj['aggregation_type'] = ApiClient.convertToType(data['aggregation_type'], 'String');
    }
    }
  return obj;
}

/**
 * The aggregation type of the KPI values. - SUM&#58; A single-value metrics aggregation type that sums up numeric values   that are extracted from KPI occurrences.
 * @member {module:model/KpiType.AggregationTypeEnum} aggregation_type
 * @default 'SUM'
 */
exports.prototype['aggregation_type'] = 'SUM';


  /**
   * Allowed values for the <code>aggregation_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AggregationTypeEnum = {
    /**
     * value: "SUM"
     * @const
     */
    "SUM": "SUM"  };

module.exports = exports;

