/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The KpiValueType model module.
 * @module model/KpiValueType
 */

/**
 * Constructs a new <code>KpiValueType</code>.
 * @alias module:model/KpiValueType
 * @class
 * @param kpiNoteName {String} The name of the kpi note associated to the occurrence with the value for this card element value type
 */
var exports = function(kpiNoteName) {
  var _this = this;

  _this['kpi_note_name'] = kpiNoteName;
};

/**
 * Constructs a <code>KpiValueType</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/KpiValueType} obj Optional instance to populate.
 * @return {module:model/KpiValueType} The populated <code>KpiValueType</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('kpi_note_name')) {
      obj['kpi_note_name'] = ApiClient.convertToType(data['kpi_note_name'], 'String');
    }
    }
  return obj;
}

/**
 * The name of the kpi note associated to the occurrence with the value for this card element value type
 * @member {String} kpi_note_name
 */
exports.prototype['kpi_note_name'] = undefined;



module.exports = exports;

