/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

var ApiClient = require('../ApiClient');



/**
 * The NumericCardElementValueType model module.
 * @module model/NumericCardElementValueType
 */

/**
 * Constructs a new <code>NumericCardElementValueType</code>.
 * the value type of a card element
 * @alias module:model/NumericCardElementValueType
 * @class
 * @param kind {module:model/NumericCardElementValueType.KindEnum} Kind of element - KPI&#58; Kind of value derived from a KPI occurrence - FINDING_COUNT&#58; Kind of value derived from a count of finding occurrences
 * @param text {String} The text of this element type
 */
var exports = function(kind, text) {
  var _this = this;

  _this['kind'] = kind;
  _this['text'] = text;
};

/**
 * Constructs a <code>NumericCardElementValueType</code> from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {module:model/NumericCardElementValueType} obj Optional instance to populate.
 * @return {module:model/NumericCardElementValueType} The populated <code>NumericCardElementValueType</code> instance.
 */
exports.constructFromObject = function(data, obj) {
  if (data) {
    obj = obj || new exports();

      if (data.hasOwnProperty('kind')) {
      obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
    }
      if (data.hasOwnProperty('text')) {
      obj['text'] = ApiClient.convertToType(data['text'], 'String');
    }
    }
  return obj;
}

/**
 * Kind of element - KPI&#58; Kind of value derived from a KPI occurrence - FINDING_COUNT&#58; Kind of value derived from a count of finding occurrences
 * @member {module:model/NumericCardElementValueType.KindEnum} kind
 */
exports.prototype['kind'] = undefined;
/**
 * The text of this element type
 * @member {String} text
 * @default ''
 */
exports.prototype['text'] = '';


  /**
   * Allowed values for the <code>kind</code> property.
   * @enum {String}
   * @readonly
   */
  exports.KindEnum = {
    /**
     * value: "KPI"
     * @const
     */
    "KPI": "KPI",
    /**
     * value: "FINDING"
     * @const
     */
    "FINDING": "FINDING"  };

module.exports = exports;

