/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.findings);
  }
}(this, function(expect, findings) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new findings.InlineResponse2001Card();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001Card', function() {
    it('should create an instance of InlineResponse2001Card', function() {
      // uncomment below and update the code to test InlineResponse2001Card
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be.a(findings.InlineResponse2001Card);
    });

    it('should have the property section (base name: "section")', function() {
      // uncomment below and update the code to test the property section
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property subtitle (base name: "subtitle")', function() {
      // uncomment below and update the code to test the property subtitle
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property findingNoteNames (base name: "finding_note_names")', function() {
      // uncomment below and update the code to test the property findingNoteNames
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property requiresConfiguration (base name: "requires_configuration")', function() {
      // uncomment below and update the code to test the property requiresConfiguration
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property badgeText (base name: "badge_text")', function() {
      // uncomment below and update the code to test the property badgeText
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property badgeImage (base name: "badge_image")', function() {
      // uncomment below and update the code to test the property badgeImage
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

    it('should have the property elements (base name: "elements")', function() {
      // uncomment below and update the code to test the property elements
      //var instance = new findings.InlineResponse2001Card();
      //expect(instance).to.be();
    });

  });

}));
