/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.findings);
  }
}(this, function(expect, findings) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new findings.InlineResponse2001Finding();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001Finding', function() {
    it('should create an instance of InlineResponse2001Finding', function() {
      // uncomment below and update the code to test InlineResponse2001Finding
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be.a(findings.InlineResponse2001Finding);
    });

    it('should have the property severity (base name: "severity")', function() {
      // uncomment below and update the code to test the property severity
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be();
    });

    it('should have the property certainty (base name: "certainty")', function() {
      // uncomment below and update the code to test the property certainty
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be();
    });

    it('should have the property nextSteps (base name: "next_steps")', function() {
      // uncomment below and update the code to test the property nextSteps
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be();
    });

    it('should have the property networkConnection (base name: "network_connection")', function() {
      // uncomment below and update the code to test the property networkConnection
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be();
    });

    it('should have the property dataTransferred (base name: "data_transferred")', function() {
      // uncomment below and update the code to test the property dataTransferred
      //var instance = new findings.InlineResponse2001Finding();
      //expect(instance).to.be();
    });

  });

}));
