/**
 * Findings API
 * The Findings API 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.findings);
  }
}(this, function(expect, findings) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new findings.InlineResponse2001Context();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001Context', function() {
    it('should create an instance of InlineResponse2001Context', function() {
      // uncomment below and update the code to test InlineResponse2001Context
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be.a(findings.InlineResponse2001Context);
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property resourceCrn (base name: "resource_crn")', function() {
      // uncomment below and update the code to test the property resourceCrn
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property resourceId (base name: "resource_id")', function() {
      // uncomment below and update the code to test the property resourceId
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property resourceName (base name: "resource_name")', function() {
      // uncomment below and update the code to test the property resourceName
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property resourceType (base name: "resource_type")', function() {
      // uncomment below and update the code to test the property resourceType
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property serviceCrn (base name: "service_crn")', function() {
      // uncomment below and update the code to test the property serviceCrn
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property serviceName (base name: "service_name")', function() {
      // uncomment below and update the code to test the property serviceName
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property environmentName (base name: "environment_name")', function() {
      // uncomment below and update the code to test the property environmentName
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property componentName (base name: "component_name")', function() {
      // uncomment below and update the code to test the property componentName
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

    it('should have the property toolchainId (base name: "toolchain_id")', function() {
      // uncomment below and update the code to test the property toolchainId
      //var instance = new findings.InlineResponse2001Context();
      //expect(instance).to.be();
    });

  });

}));
